FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.3-tf2.2-py3

RUN apt-get update && apt-get install -y portaudio19-dev libffi-dev llvm-8 python3-tk git && \
    ln -s /usr/bin/llvm-config-8 /usr/bin/llvm-config && \
    pip3 install "llvmlite==0.31.0" "numba==0.48" && \
    pip3 install pyaudio sounddevice matplotlib && \
    pip3 install librosa && \
    pip3 install git+https://github.com/keunwoochoi/kapre.git
